<script lang="ts">
  import LayoutBase from '../../../components/Layout/Admin.svelte';

  import TeamSection from '../../../components/Teams/Page/Teams_Section.svelte';

  // export let color = "light";
  let page: string = 'teams';

  let teamCommunity = [
    {
      name: 'Community of Svelte',
      img: '/images/teams/svelte.png',
      url: 'https://discord.com/invite/5Bb5yvzNPr',
      team: [
        {
          name: 'Team-Svelte #1',
          participantes: 5,
          project: 'Back End',
          status: 'completed',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 100,
          url: 'https://www.facebook.com/groups/2637132626546045',
        },
        {
          name: 'Team-Svelte #2',
          participantes: 5,
          project: 'Front End',
          status: 'on schedule',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 90,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
        {
          name: 'Team-Svelte #3',
          participantes: 3,
          project: 'Front End',
          status: 'pending',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 73,
          url: 'https://www.youtube.com/channel/UC0oi8uH1vxDcyt7b_3iByew',
        },
        {
          name: 'Team-Svelte #4',
          participantes: 5,
          project: 'Back End',
          status: 'inactive',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 73,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
      ],
    },
    {
      name: 'Community of Vue',
      img: '/images/teams/vue.png',
      url: 'https://discord.com/invite/5Bb5yvzNPr',
      team: [
        {
          name: 'Team-Vue #1',
          participantes: 5,
          project: 'Back End',
          status: 'completed',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 100,
          url: 'https://www.facebook.com/groups/2637132626546045',
        },
        {
          name: 'Team-Vue #2',
          participantes: 5,
          project: 'Back End',
          status: 'pending',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 63,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
        {
          name: 'Team-Vue #3',
          participantes: 5,
          project: 'Back End',
          status: 'on schedule',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 82,
          url: 'https://www.youtube.com/channel/UC0oi8uH1vxDcyt7b_3iByew',
        },
        {
          name: 'Team-Vue #4',
          participantes: 5,
          project: 'Front End',
          status: 'inactive',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 73,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
      ],
    },
    {
      name: 'Community of Angular',
      img: '/images/teams/angular.png',
      url: 'https://discord.com/invite/5Bb5yvzNPr',
      team: [
        {
          name: 'Team-Angular #1',
          participantes: 5,
          project: 'Back End',
          status: 'completed',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 100,
          url: 'https://www.facebook.com/groups/2637132626546045',
        },
        {
          name: 'Team-Angular #2',
          participantes: 5,
          project: 'Back End',
          status: 'pending',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 63,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
        {
          name: 'Team-Angular #3',
          participantes: 5,
          project: 'Back End',
          status: 'on schedule',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 82,
          url: 'https://www.youtube.com/channel/UC0oi8uH1vxDcyt7b_3iByew',
        },
        {
          name: 'Team-Angular #4',
          participantes: 5,
          project: 'Front End',
          status: 'inactive',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 73,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
      ],
    },
    {
      name: 'Community of React',
      img: '/images/teams/react.png',
      url: 'https://discord.com/invite/5Bb5yvzNPr',
      team: [
        {
          name: 'Team-React #1',
          participantes: 5,
          project: 'Back End',
          status: 'completed',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 100,
          url: 'https://www.facebook.com/groups/2637132626546045',
        },
        {
          name: 'Team-React #2',
          participantes: 5,
          project: 'Back End',
          status: 'pending',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 63,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
        {
          name: 'Team-React #3',
          participantes: 5,
          project: 'Back End',
          status: 'on schedule',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 82,
          url: 'https://www.youtube.com/channel/UC0oi8uH1vxDcyt7b_3iByew',
        },
        {
          name: 'Team-React #4',
          participantes: 5,
          project: 'Front End',
          status: 'inactive',
          img1: '/images/teams/angular.png',
          img2: '/images/teams/react.png',
          img3: '/images/teams/vue.png',
          img4: '/images/teams/angular.png',
          img5: '/images/teams/angular.png',
          nivel: 73,
          url: 'https://discord.com/invite/5Bb5yvzNPr',
        },
      ],
    },
  ];
</script>

<svelte:head>
  <title>Teams</title>
</svelte:head>

<LayoutBase {page}>
  <!-- <h1>Teams</h1> -->
  <TeamSection {teamCommunity} />
</LayoutBase>

<style>
</style>
